version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "3306:3306"

  app:
    depends_on:
      - mysqldb
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
